export const initialBoard = [
    [
        { unit: 'R', color: 'black', class: 'canClick', isMoved: false },
        { unit: 'N', color: 'black', class: 'canClick' },
        { unit: 'B', color: 'black', class: 'canClick' },
        { unit: 'Q', color: 'black', class: 'canClick' },
        { unit: 'K', color: 'black', class: 'canClick', isMoved: false },
        { unit: 'B', color: 'black', class: 'canClick' },
        { unit: 'N', color: 'black', class: 'canClick' },
        { unit: 'R', color: 'black', class: 'canClick', isMoved: false },
    ],
    [
        { unit: 'P', color: 'black', class: 'canClick' },
        { unit: 'P', color: 'black', class: 'canClick' },
        { unit: 'P', color: 'black', class: 'canClick' },
        { unit: 'P', color: 'black', class: 'canClick' },
        { unit: 'P', color: 'black', class: 'canClick' },
        { unit: 'P', color: 'black', class: 'canClick' },
        { unit: 'P', color: 'black', class: 'canClick' },
        { unit: 'P', color: 'black', class: 'canClick' },
    ],
    [
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
    ],
    [
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
    ],
    [
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
    ],
    [
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
        { unit: null, class: 'cantClick' },
    ],
    [
        { unit: 'P', color: 'white', class: 'canClick' },
        { unit: 'P', color: 'white', class: 'canClick' },
        { unit: 'P', color: 'white', class: 'canClick' },
        { unit: 'P', color: 'white', class: 'canClick' },
        { unit: 'P', color: 'white', class: 'canClick' },
        { unit: 'P', color: 'white', class: 'canClick' },
        { unit: 'P', color: 'white', class: 'canClick' },
        { unit: 'P', color: 'white', class: 'canClick' },
    ],
    [
        { unit: 'R', color: 'white', class: 'canClick', isMoved: false },
        { unit: 'N', color: 'white', class: 'canClick' },
        { unit: 'B', color: 'white', class: 'canClick' },
        { unit: 'K', color: 'white', class: 'canClick' },
        { unit: 'Q', color: 'white', class: 'canClick', isMoved: false },
        { unit: 'B', color: 'white', class: 'canClick' },
        { unit: 'N', color: 'white', class: 'canClick' },
        { unit: 'R', color: 'white', class: 'canClick', isMoved: false },
    ],
]